[package]
name = "null-talk-client"
version = "2.0.0"
edition = "2024"
authors = ["ByteMaster2003 <viveksahani39266@gmail.com>"]
description = "A null-safe client communication library for Rust."

[dependencies]
dashmap.workspace = true
tokio.workspace = true
tokio-util.workspace = true
futures.workspace = true
clap.workspace = true
rustls.workspace = true
tokio-rustls.workspace = true

lib = { path = "../lib" }

webpki-roots = "1.0.5"
ratatui = "0.29.0"
color-eyre = "0.6.5"
chrono = "0.4.43"
tui-textarea = "0.7.0"
