# [dm]			direct_message
# [group]		group_chat
# (required)
connection_type = "dm"

# it can be username or group name
# (required)
name = "vivek"
id = "bc7e780e2b26dec01fa791a617ef51bb93755f404a8ae150279aeb9d55d5ccab"

# encryption algorithm
# Supported algorithms: AES256, ChaCha20 --> default(AES256)
algo = "AES256"
